export const StringConstant = {
   object: 'object',
   number: 'number',
   string: 'string',
   PM: 'PM',
   AM: 'AM',
   NUMBER_REGX: "/\d+$/",
   SLIDE_URL: 'https://docs.google.com/presentation/d/1PBud_TEUVDsgT1mPUd3zLb8yniHpth5G2I7oUU81QGI/present?slide:id.g3009a3f8083_0_54',
   title: 'Salvation is here! Join our vibrant community today.!',
   required: 'required',
   email: 'email',
   INVALID_PATTERN: 'Invalid Pattern',
   MIN_LENGTH: 'Min characters should be greater than',
   MAX_LENGTH: 'Max characters should not be exceeded',
   maxlength: 'maxlength',
   minlength: 'minlength',
   pattern: 'pattern',
   REUIRED: 'Required',
   DATE_PICKER_PARSE: 'matDatepickerParse',
   MIN_DATE_PCIKER: 'matDatepickerMin',
   MAX_DATE_PCIKER: 'matDatepickerMax',
   INVALID_FORMAT: 'Invalid Format',
   MIN_DATE_ERROR: 'Date Should not less than',
   MAX_DATE_ERROR: 'Date Should not greater than',
   ALLOWED: 'Allowed only',
   xlsxExtension: '.xlsx',
   TRANS: 'transliteration',
   LOGIN_TITLE: 'Login to Discover',
   LOGIN_DES: 'May your heart be filled with peace and your spirit be renewed as you connect with us',
   INVALID_EMAIL: 'Invalid email',
   passwordKey: 'ggmchurch@2001',
   RECENTLY_VIEWD: 'Recently Viewed',
   NO_BOOKMARKS_FOUND: 'No Bookmarks Found.!',
   bg_error: 'bg-error',
   bg_success: 'bg-success',
   w_100: 'wt-100',
   ERROR_MSG: 'Please try again.!',
   CREATE_SUCCESS: 'Records created successfully.!',
   file: 'file',
   NAME: 'name',
   XLSX: 'xlsx',
   xls: 'xls',
   TM_ZIP_FILE_NAME: 'training-materials',
   FILE: 'File',
   LEFT: 'left',
   array: 'array',
   none: 'none',
   SEARCH_RESULT: 'Search Result',
   WITHDRAW_TITLE: 'WITHDRAW_TITLE',
   delete: 'delete',
   IN_ACTIVE_RECORDS: 'IN_ACTIVE_RECORDS',
   GLOBAL_RESULT: 'Fetched the global result.!',
   TRUE: 'true',
   FALSE: 'false',
   titleCol: 'A1',
   A: 'A',
   DEFUALT_SHEET: 'Sheet 1',
   underScore: '_',
   hyphen: ' - ',
   invalidDate: 'Invalid date',
   quizResult: 'Quiz Result',
    NoOfQuestions : 'NoOfQuestions',
    click : 'click',
    printsectionid : 'printsectionid',
    boxShadow : 'mat-elevation-z8',
    border : 'border',
    mt5 : 'mt-5',
    primary : 'primary',
    page_title : 'page_title',
    pdf : 'pdf',
} 
