export enum DataTableHeaderMapper {
    std_id = "Student Id",
    name = 'Student Name',
    comments = "Remarks",
    createdBy = "Created By",
    creationDate = "Creation Date",
    createdDate = "Created Date",
    deletedBy = "Deleted By",
    deletionDate = "Deletion Date",
    deletionFlag = "Status",
    modificationDate = "Modification Date",
    modifiedBy = "Modified By",
    status = "status",
    class = "Class",
    age = "Age",
    phoneNum = "Phone Number",
    question = "Question",
    answer = "Auestion",
    category = "Category",
    questionId = 'Question Id',
    rank = "Rank",
    percentage = "Percentage",
    correctAnswers = "Correct Answers",
    wrongAnswers = "Wrong Ans",
    totalQuestions = "Total Questions",
    organisedBy = "Organised By",
    score = "Earned Points"
  }
  